### ISSUE TITLE
Proposal: Use old-style object method shorthand.

### ISSUE THREAD

**Issue by davidtimmons** [Roll-Forward/javascript#1]
**Rule:**
https://github.com/Roll-Forward/javascript#es6-object-shorthand

**Proposed Change:**
<a name="es6-object-shorthand"></a><a name="3.5"></a>
  - [3.3](#es6-object-shorthand) Avoid object method shorthand. eslint: [`object-shorthand`](https://eslint.org/docs/rules/object-shorthand.html) jscs: [`requireEnhancedObjectLiterals`](http://jscs.info/rule/requireEnhancedObjectLiterals)

    > Why? Using old-style object method notation makes it clearer what keys are in the object without having to take the mental step of transforming the function name into an object key.

    ```javascript
    // bad
    const atom = {
      value: 1,

      addValue(value) {
        return atom.value + value;
      },
    };

    // good
    const atom = {
      value: 1,

      addValue: function (value) {
        return atom.value + value;
      },
    };
    ```

**Opinion:**
Using old-style object method notation makes it clearer what keys are in the object without having to take the mental step of transforming the function name into an object key.

**Comment by acoulon99** [comment]
Sounds good to me

**Comment by davidtimmons** [comment]
#12
