### ISSUE TITLE
Proposal: Allow eval() in rare situations.

### ISSUE THREAD

**Issue by davidtimmons** [Roll-Forward/javascript#2]
**Rule:**
https://github.com/Roll-Forward/javascript#strings--eval

**Proposed Change:**
<a name="strings--eval"></a><a name="6.5"></a>
  - [6.4](#strings--eval) Only use `eval()` in rare situations as it can open security and performance vulnerabilities. Never use `eval()` on an untrusted string such as user input or an HTTP response.

**Opinion:**
There is rarely a need to use `eval()`, but it can be useful in very limited situations. When evaluating code you wrote, I would argue there are no security threats (only potential performance traps). See: https://www.bennadel.com/blog/1926-exploring-javascript-s-eval-capabilities-and-closure-scoping.htm

**Comment by acoulon99** [comment]
Perhaps on a situational basis? If we encounter a use case for using `eval()`, we could have a team discussion within the PR? My primary concern is team awareness.

**Comment by davidtimmons** [comment]
Uses for this are rare enough that I'm okay leaving out this change. If we encounter a need for it, we can manually flag off the linter around the impacted code. In fact, that may be a better solution. Explicitly enabling this feature where needed calls out the risk of using it.
