### ISSUE TITLE
Proposal: Allow standard function declarations.

### ISSUE THREAD

**Issue by davidtimmons** [Roll-Forward/javascript#3]
**Rule:**
https://github.com/Roll-Forward/javascript#functions--declarations

**Proposed Change:**
Remove the rule.

**Opinion:**
Assigning functions to a variable is a great part of the JavaScript language. However, I think forgoing standard function definitions entirely is a step too far that can hurt readability. I don't see function hoisting as a big problem. In fact, we use it in our Angular code.

**Comment by acoulon99** [comment]
Perhaps on a situational basis? If we encounter a use case for using it, we could have a team discussion within the PR? My primary concern is team awareness.

**Comment by davidtimmons** [comment]
A team discussion around function declarations? To be clear, are you saying you think we should outlaw `function myFunction() {...}`?

**Comment by acoulon99** [comment]
My comment was weird, haha.. I'm totally ok with allowing `function theFunction(){...}`

**Comment by davidtimmons** [comment]
#12
