### ISSUE TITLE
Proposal: Vertically align long control statements.

### ISSUE THREAD

**Issue by davidtimmons** [Roll-Forward/javascript#6]
**Rule:**
https://github.com/Roll-Forward/javascript#control-statements

**Proposed Change:**
<a name="control-statements"></a>
  - [17.1](#control-statements) In case your control statement (`if`, `while` etc.) gets too long or exceeds the maximum line length, each (grouped) condition should be put into a new line with operators vertically right-aligned. The logical operator should begin the line.

    > Why? Requiring operators at the beginning of the line keeps the operators aligned and follows a pattern similar to method chaining. This also improves readability by making it easier to visually follow complex logic.

    ```javascript
    // bad
    if ((foo === 123 || bar === 'abc') && doesItLookGoodWhenItBecomesThatLong() && isThisReallyHappening()) {
      thing1();
    }

    // bad
    if (foo === 123 &&
      bar === 'abc') {
      thing1();
    }

    // bad
    if (foo === 123
      && bar === 'abc') {
      thing1();
    }

    // bad
    if (
      foo === 123 &&
      bar === 'abc'
    ) {
      thing1();
    }

    // bad
    if (
      foo === 123
      && bar === 'abc'
    ) {
      thing1();
    }

    // good
    if ( foo === 123
      && bar === 'abc'
    ) {
      thing1();
    }

    // good
    if ( (foo === 123 || bar === "abc")
      && doesItLookGoodWhenItBecomesThatLong()
      && isThisReallyHappening()
    ) {
      thing1();
    }

    // good
    if (foo === 123 && bar === 'abc') {
      thing1();
    }
    ```

**Opinion:**
Readability improves when the logical expressions are vertically aligned.

**Comment by acoulon99** [comment]
Sounds good to me!

**Comment by davidtimmons** [comment]
I played around with this rule over the weekend, and I think I actually like the original way this was written in the Airbnb guide better. Closing the issue unless there are objections.
