### ISSUE TITLE
Proposal: Use // for internal multi-line comments and /***/ for formal definitions.

### ISSUE THREAD

**Issue by davidtimmons** [Roll-Forward/javascript#7]
**Rule:**
https://github.com/Roll-Forward/javascript#comments--multiline

**Proposed Change:**
<a name="comments--multiline"></a><a name="17.1"></a>
  - [18.1](#comments--multiline) Use `/** ... */` for multi-line comments when used to describe a function or module. Use `//` for multi-line comments when used elsewhere.

    > Why? Using the `/**...*/` notation for function and module descriptions is practically an industry standard. Using `//` elsewhere distinguishes internal notes from more formal descriptions. `//` is also the default format for many IDEs when commenting multiple lines.

    ```javascript
    // bad
    // make() returns a new element
    // based on the passed in tag name
    //
    // @param {String} tag
    // @return {Element} element
    function make(tag) {

      // ...

      return element;
    }

    // good
    /**
     * make() returns a new element
     * based on the passed-in tag name
     */
    function make(tag) {

      // ...

      return element;
    }

    // good
    /**
     * make() returns a new element
     * based on the passed-in tag name
     */
    function make(tag) {

      // These are some notes.
      // Reading these are critical to understanding
      // why this function behaves as it does.

      return element;
    }

    // good
    // These are some notes.
    // Reading these are critical to understanding
    // why this global variable behaves as it does.
    const Foo = bar()(baz);
    ```

**Opinion:**
Using the `/**...*/` notation for function and module descriptions is practically an industry standard. Using `//` elsewhere distinguishes internal notes from more formal descriptions. `//` is also the default format for many IDEs when commenting multiple lines.

**Comment by acoulon99** [comment]
yeah, this makes sense to me as well. It seems better to use the 2 ways to comment to distinguish between 2 types of comments, instead of an indicator of the number of lines the comment is.

**Comment by davidtimmons** [comment]
#12
