### ISSUE TITLE
Proposal: Use 4-space indention.

### ISSUE THREAD

**Issue by davidtimmons** [Roll-Forward/javascript#8]
**Rule:**
https://github.com/Roll-Forward/javascript#es6-object-shorthand

**Proposed Change:**
<a name="whitespace--spaces"></a><a name="18.1"></a>
  - [19.1](#whitespace--spaces) Use soft tabs (space character) set to 4 spaces. eslint: [`indent`](https://eslint.org/docs/rules/indent.html) jscs: [`validateIndentation`](http://jscs.info/rule/validateIndentation)

    ```javascript
    // bad
    function foo() {
    ∙∙let name;
    }

    // bad
    function bar() {
    ∙let name;
    }

    // good
    function baz() {
    ∙∙∙∙let name;
    }
    ```

**Opinion:**
We use 4-space indention in the rest of our code.

**Comment by acoulon99** [comment]
Sounds good

**Comment by davidtimmons** [comment]
#12
