### ISSUE TITLE
Proposal: Allow names with a leading underscore.

### ISSUE THREAD

**Issue by davidtimmons** [Roll-Forward/javascript#9]
**Rule:**
https://github.com/Roll-Forward/javascript#naming--leading-underscore

**Proposed Change:**
Remove this rule.

**Opinion:**
Anyone who has spent any time with JavaScript knows `_` does not automatically make something private. When used as shorthand to communicate intent, such as "this is a helper function that will not be exported", it improves the ability to reason about the code in a single character.

**Comment by acoulon99** [comment]
Sounds ok to me. Using comments and/or `module.exports` should be clear enough in my opinion.

**Comment by davidtimmons** [comment]
#12
